log:
  level: debug
deployers:
  image:
    deployer_name: podman
    deployment:
      host:
        NetworkMode: "host" # Needed local clusters only.
      imagePullPolicy: IfNotPresent
logged_outputs:
  error:
    level: debug
